import { useState } from 'react'
import { Check, ChevronLeft, ChevronRight, MessageCircle, Palette, Settings2, ShieldCheck } from 'lucide-react'

const steps=[['Widget Details',Settings2],['Customize',Palette],['Install & Publish',ShieldCheck]]
export default function WebsiteWidgetPage(){
  const [step,setStep]=useState(0)
  const [form,setForm]=useState({name:'test',message:'Hello! Welcome to Queens Collection!',code:'India (+91)',phone:'91773352',auto:false,bubble:true,position:'Right',cta:'Chat with us',color:'#1689f5',radius:16})
  const set=(k,v)=>setForm(x=>({...x,[k]:v}))
  return <div className="mx-auto w-full max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8">
    <div className="mb-5"><h1 className="text-2xl font-bold">Widget</h1><p className="mt-1 text-sm text-slate-500">WhatsApp <span className="mx-1">•</span> Widget <span className="mx-1">•</span> Create Widget</p></div>
    <div className="mb-6 grid gap-2 md:grid-cols-3">{steps.map(([name,Icon],i)=><div key={name} className={`flex items-center gap-3 rounded-xl border px-4 py-3 ${i===step?'border-blue-200 bg-blue-50':'border-slate-200 bg-white'}`}><div className={`grid h-8 w-8 place-items-center rounded-full text-sm font-bold ${i<step?'bg-emerald-500 text-white':i===step?'bg-blue-600 text-white':'bg-slate-100 text-slate-400'}`}>{i<step?<Check size={16}/>:i+1}</div><div><p className="text-xs text-slate-400">Step {i+1}</p><p className={`font-semibold ${i===step?'text-blue-700':'text-slate-700'}`}>{name}</p></div></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1fr_360px]">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
        {step===0&&<div className="grid gap-5 md:grid-cols-2"><label><span className="mb-1.5 block text-sm font-medium">Widget Name</span><input value={form.name} onChange={e=>set('name',e.target.value)} className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500"/></label><label><span className="mb-1.5 block text-sm font-medium">Default Pre-filled Message</span><input value={form.message} onChange={e=>set('message',e.target.value)} className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500"/></label><label><span className="mb-1.5 block text-sm font-medium">Country Code</span><select value={form.code} onChange={e=>set('code',e.target.value)} className="w-full rounded-xl border border-slate-200 px-4 py-3"><option>India (+91)</option><option>USA (+1)</option><option>UK (+44)</option></select></label><label><span className="mb-1.5 block text-sm font-medium">WhatsApp Phone Number</span><input value={form.phone} onChange={e=>set('phone',e.target.value)} className="w-full rounded-xl border border-slate-200 px-4 py-3"/></label><Toggle label="Enable Chat Widget on Mobile Devices" value={form.bubble} onChange={v=>set('bubble',v)}/><Toggle label="Enable Button Animation" value={form.auto} onChange={v=>set('auto',v)}/></div>}
        {step===1&&<div className="grid gap-5 md:grid-cols-2"><label><span className="mb-1.5 block text-sm font-medium">Position</span><select value={form.position} onChange={e=>set('position',e.target.value)} className="w-full rounded-xl border border-slate-200 px-4 py-3"><option>Right</option><option>Left</option></select></label><label><span className="mb-1.5 block text-sm font-medium">CTA Text</span><input value={form.cta} onChange={e=>set('cta',e.target.value)} className="w-full rounded-xl border border-slate-200 px-4 py-3"/></label><label><span className="mb-1.5 block text-sm font-medium">Widget Button Size</span><input type="range" min="44" max="84" className="w-full"/></label><label><span className="mb-1.5 block text-sm font-medium">Border Radius (px)</span><input type="number" value={form.radius} onChange={e=>set('radius',e.target.value)} className="w-full rounded-xl border border-slate-200 px-4 py-3"/></label><label className="md:col-span-2"><span className="mb-1.5 block text-sm font-medium">Button Background</span><div className="flex items-center gap-3"><input type="color" value={form.color} onChange={e=>set('color',e.target.value)} className="h-11 w-20 rounded border"/><input value={form.color} onChange={e=>set('color',e.target.value)} className="rounded-xl border border-slate-200 px-4 py-3"/></div></label></div>}
        {step===2&&<div className="space-y-5"><div className="rounded-xl border border-blue-100 bg-blue-50 p-4"><p className="font-semibold text-blue-900">Install your widget</p><p className="mt-1 text-sm text-blue-700">Copy this code and paste it before the closing &lt;/body&gt; tag on your website.</p></div><pre className="overflow-x-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-100">{`<script src="https://cdn.example.com/widget.js" data-phone="${form.phone}" data-message="${form.message}"></script>`}</pre><button onClick={()=>navigator.clipboard?.writeText(`<script data-phone="${form.phone}"></script>`)} className="rounded-xl border px-4 py-2.5 font-medium">Copy Code</button></div>}
        <div className="mt-8 flex justify-end gap-3 border-t pt-5"><button onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={step===0} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 font-medium disabled:opacity-40"><ChevronLeft size={17}/> Back</button>{step<2?<button onClick={()=>setStep(s=>s+1)} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 font-semibold text-white">Next <ChevronRight size={17}/></button>:<button className="rounded-xl bg-blue-600 px-5 py-2.5 font-semibold text-white">Publish Widget</button>}</div>
      </section>
      <aside className="rounded-2xl border border-slate-200 bg-slate-50 p-6"><p className="mb-4 text-sm font-semibold text-slate-600">Live Preview</p><div className="relative min-h-[500px] overflow-hidden rounded-2xl border bg-white p-5"><div className="absolute inset-x-5 bottom-20 rounded-2xl border bg-white p-4 shadow-lg"><p className="font-semibold">Queens Collection</p><p className="mt-2 text-sm text-slate-600">{form.message}</p></div><button style={{backgroundColor:form.color,borderRadius:`${form.radius}px`}} className={`absolute bottom-5 ${form.position==='Left'?'left-5':'right-5'} inline-flex items-center gap-2 px-4 py-3 font-semibold text-white shadow-lg ${form.auto?'animate-bounce':''}`}><MessageCircle size={20}/>{form.cta}</button></div></aside>
    </div>
  </div>
}
function Toggle({label,value,onChange}){return <label className="flex items-center gap-3 rounded-xl border border-slate-200 p-4"><button type="button" onClick={()=>onChange(!value)} className={`relative h-6 w-11 rounded-full transition ${value?'bg-blue-600':'bg-slate-300'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${value?'left-6':'left-1'}`}/></button><span className="text-sm text-slate-700">{label}</span></label>}
